<li class="archive-thumb">
                <article>
                  <h2><a href="[field:arcurl/]"title="[field:fulltitle/]">[field:fulltitle/]</a></h2>
                  <a class="pic float-left"href="[field:arcurl/]"title="[field:fulltitle/]"><img class="lazy"src="[field:litpic/]"style="height:120px; width:180px"/></a>
                  <p>[field:description/]...</p>
                  <p class="post-meta"><span><i class="icon-user"></i>[field:writer/]</span><span><i class="icon-time"></i>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span><span><i class="icon-eye-open"></i>[field:click/]</span><span><i class="icon-comment-alt"></i><a href="[field:arcurl/]#comments"title="[field:fulltitle/]上的评论"><span class="ds-thread-count"data-thread-key="[field:id/]"data-count-type="comments"></span>评论</a></span><span><i class="icon-tag"></i>[field:id function='nic_arc_tag_link(@me)'/]</span></p>
                  <div class="clear"></div>
                </article>
              </li>