<?php
$z[0]=Array("field","",11,37);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",46,69);
$z[1][4]['name']="id";
$z[2]=Array("field","",77,105);
$z[2][4]['name']="typeurl";
$z[3]=Array("global","",142,166);
$z[3][4]['name']="itemindex";
$z[4]=Array("field","",172,201);
$z[4][4]['name']="typename";
$z[5]=Array("channel","\r\n            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            ",252,391);
$z[5][4]['type']="son";
$z[5][4]['noself']="yes";

?>