<?php
$z[0]=Array("field","",100,119);
$z[0][4]['name']="title";
$z[1]=Array("global","",120,146);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",186,208);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",246,297);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1328,1363);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1598,1627);
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n              <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n              ",1878,2126);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li class='current-menu-item'><a href='~typelink~'>~typename~</a> </li>";
$z[7]=Array("type","[field:typename/]",2370,2410);
$z[8]=Array("field","",2490,2511);
$z[8][4]['name']="content";
$z[9]=Array("include","",2634,2671);
$z[9][4]['filename']="footer.htm";

?>