<?php
$z[0]=Array("global","",203,229);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",241,267);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",1928,1949);
$z[2][4]['name']="qqmail";
$z[3]=Array("global","",2356,2381);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("field","(@me==\"\")?@me=\" class='current-menu-item'\":@me=\"\";",2858,2960);
$z[4][4]['name']="typeid";
$z[4][4]['runphp']="yes";
$z[5]=Array("field","",2968,2994);
$z[5][4]['name']="currentstyle";
$z[6]=Array("global","",3023,3049);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("channelartlist","\r\n        <li class=\"{dede:field.currentstyle/}\"><a id=\"{dede:field name='id'/}\" href=\"{dede:field name='typeurl'/}\"> <i class=\"icon-fixed-width icon-00{dede:global.itemindex/}\"></i>{dede:field name='typename'/}</a>\r\n          <ul class=\"sub-menu\">\r\n            {dede:channel type='son' noself='yes'}\r\n            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            {/dede:channel}\r\n          </ul>\r\n        </li>\r\n        ",3130,3644);
$z[7][4]['typeid']="1,2,3,33,9";
$z[7][4]['row']="5";
$z[8]=Array("field","",3665,3691);
$z[8][4]['name']="currentstyle";

?>