<?php
$z[0]=Array("field","",100,119);
$z[0][4]['name']="title";
$z[1]=Array("global","",120,146);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",186,215);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",253,311);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1670,1705);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1960,1989);
$z[5][4]['name']="position";
$z[6]=Array("type","&nbsp;分类：[field:typename/]<a class=\"rss-cat-icon\"title=\"订阅这个分类\"href=\"[field:typelink /]\"><i class=\"icon-rss\"></i></a>",2634,2783);
$z[7]=Array("field","",2855,2912);
$z[7][4]['name']="description";
$z[7][4]['function']="html2text(@me)";
$z[8]=Array("list","\r\n              <li class=\"archive-simple\">\r\n                <h2><a href=\"[field:arcurl/]\" title=\"[field:title/]\" rel=\"bookmark\"><i class=\"icon-angle-right\"></i>[field:title/]</a></h2>\r\n                <p class=\"post-meta\"> <span><i class=\"icon-time\"></i>[field:pubdate function=\"GetDateMK(@me)\"/]</span><span><i class=\"icon-eye-open\"></i>[field:click/]</span> </p>\r\n              </li>\r\n              ",3032,3494);
$z[8][4]['row']="20";
$z[8][4]['pagesize']="20";
$z[8][4]['titlelen']="30";
$z[9]=Array("pagelist","",3550,3627);
$z[9][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",3734,3770);
$z[10][4]['filename']="right.htm";
$z[11]=Array("include","",3816,3853);
$z[11][4]['filename']="footer.htm";

?>