<?php
$z[0]=Array("arclist","\r\n      <li>\r\n        <div class=\"widget-thumb\"> <a class=\"post-thumbnail\" href=\"[field:arcurl/]\" title=\"[field:title /]\" rel=\"bookmark\"><img class=\"lazy\" src=\"[field:litpic/]\" style=\"height:45px; width:45px\"/></a> <a href=\"[field:arcurl/]\" title=\"[field:title /]\">[field:title /]</a><span class=\"date\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span> </div>\r\n      </li>\r\n      ",829,1276);
$z[0][4]['row']="10";
$z[0][4]['titlelen']="46";
$z[0][4]['orderby']="id";
$z[1]=Array("arclist","\r\n        <li>\r\n          <div class=\"widget-thumb\"> <a class=\"post-thumbnail\" href=\"[field:arcurl/]\" title=\"[field:title /]\" rel=\"bookmark\"><img class=\"lazy\" src=\"[field:litpic/]\" style=\"height:45px; width:45px\"/></a> <a href=\"[field:arcurl/]\" title=\"[field:title /]\">[field:title /]</a><span class=\"date\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span> </div>\r\n        </li>\r\n        ",1601,2056);
$z[1][4]['row']="5";
$z[1][4]['titlelen']="46";
$z[1][4]['orderby']="hot";
$z[2]=Array("tag"," <a data-original-title=\"[field:count/]个话题\" title=\"[field:count/]个话题\" href=\"[field:link/]\"> [field:tag/] ([field:count/]) </a> ",2382,2558);
$z[2][4]['sort']="hot";
$z[2][4]['getall']="2";

?>